### ISSUE TITLE
New release plans ?

### ISSUE THREAD

**Issue by mariogarcia** [adamldavis/groocss#18]
Hi:

I've started using Groocss + Asset-Pipeline to create the sites of some open source projects of mine but there are some features  from GrooCSS, like deep nested styles for example, that are not working in any of the published releases so far.

Is there any plans to release a new version soon ?

Of course I'd be glad to help. 

And congrats for the project BTW.
Mario

**Comment by adamldavis** [comment]
Hi Mario,
My apologies but my interests are elsewhere these days, so I don't plan on
updating it. If you make a pull request I would look at it, but it might
take awhile.

Thanks,
Adam

**Comment by mariogarcia** [comment]
Thanks for your quick response. No worries. Then I'll be probably working on a fork.

Only one more question, Do you remember why did you decide to go for different groovy targets ? groocss-1.0-groovy-2.4, groocss-1.0-groovy-2.5...etc ? I'm asking this because the project I want to be align with is asset-pipeline and I see that project only uses the same groovy version for everything.  Did you have a specific use case ? 

All the best
Mario

**Comment by adamldavis** [comment]
I think that was to avoid conflicts with other libraries that rely on
Groovy.  From what I remember spock did this as well.

**Comment by mariogarcia** [comment]
Thanks for the quick response, I'll keep it in mind. 
Mario
