### ISSUE TITLE
Allow conversion that's not dependent on Files

### ISSUE THREAD

**Issue by craigburke** [adamldavis/groocss#2]
Very cool project. I'm interested to see how it evolves.

I was thinking it would be nice to be able to covert a String value instead of having input and output files (something like this):

``` groovy
String grooCss = "p { border '1px solid black'}"
String result = GrooCSS.covert(grooCss)
```

Even a convert method that used an `InputStream` and an `OutputStream` would give some more flexibility and allow it to be used in a project like [the Asset Pipeline](https://github.com/bertramdev/asset-pipeline).

**Comment by adamldavis** [comment]
Thanks for the interest. This is a great idea!

**Comment by adamldavis** [comment]
Added several varieties of convert (and synonymous "process") that take String, InputStream & OutputStream, or Reader & PrintWriter. All take an optional _Config_ parameter, and optional charset which defaults to _UTF-8_. Closing.
